### ISSUE TITLE
請問要將小屋做成RSS應該怎麼做

### ISSUE THREAD

**Issue by aaa2800160** [jlhg/gamer-rssgen#1]
請問要將小屋做成RSS應該怎麼做

**Comment by cldotdev** [comment]
如果是小屋的創作，可以抓以下網址 (`<ID>` 是作者ID)

`https://home.gamer.com.tw/creation.php?owner=<ID> `

用正規表示從以下區塊去抓作者/標題/內容/連結/發表時間

```
<div class="BH-lbox"><!--區塊1開始-->
...
</div>
```

概念上是這樣，找時間再來實作看看。

**Comment by aaa2800160** [comment]
不好意思拖了很久才回應
嗯...這種RSS的架設方法我可以確認一下嗎
我對程式代碼不懂 在這裡聊方便嗎
我是想使用ifttt的透過RSS連結Webhooks 但不熟悉
這種應該不是改網址就能成立的吧
需要自行架設執行才能掃描或透過雲端運算之類的 
所以想詢問 透過Google的那服務就能自動更新Rss了嗎還是手動 以及其方法只要將那區塊修改其他不用改就能使用了嗎
在考慮是利用網路上的RSS連結生產器比較方便還是雲端運算方便 免費的RSS生產器好像6小時更新一次 付費也1小時

**Comment by cldotdev** [comment]
Google Apps Script 的 RSS feed 產生原理是當使用者點擊網址時，即時將目標網站的網頁轉換成 RSS 格式並回傳給使用者，所以將該網址丟給 IFTTT 或是其他 RSS 閱讀器就可以達到訂閱的效果。至於更新的時間端看 IFTTT 跟閱讀器的抓取頻率而定。要抓其他網站就是修改原始碼的正規表示式，並把解析到的資料傳到相應的變數即可。

除了巴哈新聞以外，我現在不用 Google Apps Script 去訂閱哈拉區看板了，因為GAS Quota 限制是帳號的總限制，一旦訂閱看板數量太多就會出現錯誤，現在都是用自租的伺服器寫 script 去轉。

網路上的 RSS 連結生產器，有更新時間的通常都是主動向目標網站抓取然後提供 Cache。如果目標網站更新頻率不高，用免費的好像也就足夠，穩定度如何就不知道了。

**Comment by aaa2800160** [comment]
所以您是自行租借雲端運算服務來執行的對嗎
考慮到可能有問題可能用免費的生產器就好
不過這邊Google多的是 因此不在考慮範圍 但如果這服務是付費或需要認信用卡才能免費試用我可能無法使用 只是您說的點擊網址 代表著這一樣需要手動更新是嗎
是說方便看已完成編輯的代碼嗎 比對看看哪邊可以改變一下來完成RSS
另外其實GNN的RSS官方就有提供了 對著訂閱那邊按下去會出現連結 如下
https://gnn.gamer.com.tw/rss.xml
是說您的訂閱訊息都傳至哪裡
我都藉由Discord這種自由度很高的留言板方便整理 裡面一個群組(伺服器)可以分好幾個頻道 既不會洗版又可以方便分開

**Comment by cldotdev** [comment]
巴哈小屋的 RSS 可以參考我寫的 code: https://github.com/jlhg/gamer-rssgen/blob/master/src/gamer-home.js

利用 Google Apps Script 產生應用程式網址後，將網址貼到 IFTTT 的 RSS Feed Trigger，然後選擇 Webhooks action，就可以設定給 Discord 或其他網站使用。

<img width="559" alt="2018-10-04 02 05 02" src="https://user-images.githubusercontent.com/2265716/46429808-ec0c4f00-c779-11e8-8a48-c6b266b685a0.png">

我自己是用 Inoreader 閱讀器，將產生後的網址丟給 Inoreader 他就會自動更新。

**Comment by aaa2800160** [comment]
謝謝 找時間用電腦試試看

**Comment by cow03haha** [comment]
大大這樣用對嗎?
我是想要用webhook把它連結到discord
但沒用QQ
求解(我用場外來測試)
另外子版也可以嗎?
感恩
![66119359-1271fe00-e60b-11e9-82c4-737a3d2e9961](https://user-images.githubusercontent.com/44705326/66189044-6cca9780-e6bb-11e9-9c0c-724b61f965bb.png)
![image](https://user-images.githubusercontent.com/44705326/66119383-1c93fc80-e60b-11e9-9530-d0de6cc254af.png)

**Comment by cldotdev** [comment]
> 大大這樣用對嗎?
> 我是想要用webhook把它連結到discord
> 但沒用QQ
> 求解(我用場外來測試)
> 另外子版也可以嗎?
> 感恩

你是直接用這個專案的程式碼嗎？

因為這專案滿久沒維護了，加上巴哈的網站也有改版，所以裡面的程式碼應該是壞的。

我有開一個新專案 (https://github.com/jlhg/feedgen) 用原生的程式轉，有架在 Heroku 免費版上。
如果你有這個需求，我就再把巴哈姆特哈拉區也加進去。

**Comment by cow03haha** [comment]
> 你是直接用這個專案的程式碼嗎？

我是自己再用你的程式碼架的,因為我有學術帳號好像可以增加你說的quota上限?
> 因為這專案滿久沒維護了，加上巴哈的網站也有改版，所以裡面的程式碼應該是壞的。
>
> 我有開一個新專案 (https://github.com/jlhg/feedgen) 用原生的程式轉，有架在 Heroku 免費版上。
> 如果你有這個需求，我就再把巴哈姆特哈拉區也加進去。

那就麻煩大大了:3 我是有管理一個discord遊戲群,所以想說用webhook來讓玩家及時了解第一手資訊

**Comment by cldotdev** [comment]
@cow03haha 

可以試試看以下網址：

```
https://feedgen.org/gamer_forum/{bsn}
```

其中 bsn 就是哈拉區網址上的 bsn 參數，代進去就可以得到那個板的 RSS。

e.g. 

場外休憩

```
https://feedgen.org/gamer_forum/60076
```

另外如果想過濾只要 GP 數 > 5 的文章，後面加上 `?gp=5` 這個參數：

```
https://feedgen.org/gamer_forum/60076?gp=5
```

gp 參數值可以是 5/20/50/100/200

**Comment by cow03haha** [comment]
還是不行,是我設定錯誤嗎
![error](https://user-images.githubusercontent.com/44705326/68082400-0b7f1b00-fe57-11e9-8f3f-d79e46c16642.png)

**Comment by cow03haha** [comment]
感謝,可以正常使用,但是會延遲(突然一次通知很多篇,但免費版也沒甚麼好要求的是吧w)
另外想問一下還有辦法訂閱特定分類嗎?

**Comment by cldotdev** [comment]
抱歉，因為重構的關係，API 有變，哈拉區的 feed 取得網址改為：

```
https://feedgen.org/gamer_forum?bsn=23805
```

另外新增 search:tkeyword 參數，可以過濾標題符合關鍵字的文章。

假如想要訂閱【攻略】分類的文章，feed 網址為：

```
https://feedgen.org/gamer_forum?bsn=23805&search:tkeyword=【攻略】
```

>感謝,可以正常使用,但是會延遲(突然一次通知很多篇,但免費版也沒甚麼好要求的是吧w)

會延遲應該是跟 IFTTT 設定的觸發更新間隔時間有關

**Comment by ToffeeNeko** [comment]
感谢大大。之前一直在用RSSHub生成的巴哈订阅源，但唯独不支持哈拉区。。终于找到可用的源了

**Comment by hykenblue** [comment]
大大您好，請問這個巴哈姆特RSS 能加上一個縮略圖鏈接嗎？

**Comment by cldotdev** [comment]
> 大大您好，請問這個巴哈姆特RSS 能加上一個縮略圖鏈接嗎？

不太懂你說的縮略圖是指什麼? 目前這個 Google Apps Script 產生器我已經沒在用 & 維護了。
